import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import {
  NextAuthSessionProvider,
  ReactQueryProvider,
} from "@/app/lib/providers";
import { Toaster } from "react-hot-toast";
import Layout from "@/app/components/layout";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IFeedly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <NextAuthSessionProvider>
          <ReactQueryProvider>
            <Layout>{children}</Layout>
          </ReactQueryProvider>
        </NextAuthSessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
